[package]
name = "reselim/roact-router"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "src"]

[dependencies]
Roact = "roblox/roact@1.4.0"